import React, { useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';

import Keyboard from '../components/Keyboard';
import Layout from '../components/Layout';
import scales, { ScaleDefinition } from '../lib/scales';

const HomePage: NextPage = () => {
  const [scale, setScale] = useState<ScaleDefinition | null>(scales[1]);
  const [root, setRoot] = useState(3);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Pianoapp</h1>
      </header>
      <main>
        <Keyboard keys={24} root={root} offset={-7} scale={scale} />
      </main>
    </Layout>
  );
};

export default HomePage;
